# Generated by Django 5.0.6 on 2025-03-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reporting_manager',
        ),
    ]
