# Generated by Django 5.0.6 on 2025-03-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_department_table_alter_role_table_euser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='euser',
            options={},
        ),
        migrations.AlterModelTable(
            name='euser',
            table='employee',
        ),
    ]
